### ISSUE TITLE
Meeting request

### ISSUE THREAD

**Issue by andrewleber** [malikxomer/static#1]
Hello Mr Omer.

I have reason to believe that you are a talented engineer. We're always on the lookout for top talent, and would love to chat with you. 

Please email me at andrew@strainbra.in and we can set up a time to talk.

Best,
Andrew

**Comment by malikxomer** [comment]
Hi Mr Andrew,

I hope this email finds you in the best of your health. I would love to have a chat with you at a time we can decide mutually. Looking forward to you

Thanks & Regards,
Muhammad Omer
Software Engineer
